# Generated by Django 5.2.8 on 2025-12-03 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_starling", "0001_initial"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsSettings",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable analytics tracking across the site",
                    ),
                ),
                (
                    "head_tracking_code",
                    models.TextField(
                        blank=True,
                        help_text="Analytics tracking code to insert in <head> section (e.g., Google Analytics, Matomo). Include <script> tags.",
                    ),
                ),
                (
                    "body_tracking_code",
                    models.TextField(
                        blank=True,
                        help_text="Analytics tracking code to insert at the end of <body> section (e.g., Google Tag Manager noscript). Include <noscript> or <script> tags.",
                    ),
                ),
                (
                    "inclusion_mode",
                    models.CharField(
                        choices=[
                            ("all", "Include on all pages (default)"),
                            ("specific", "Include only on specific pages"),
                            ("exclude", "Include on all pages except specific pages"),
                        ],
                        default="all",
                        help_text="Control which pages include analytics",
                        max_length=20,
                    ),
                ),
                (
                    "excluded_pages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pages to exclude from analytics (when 'Include on all pages except specific pages' is selected)",
                        related_name="analytics_excluded",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "included_pages",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Pages to include analytics on (when 'Include only on specific pages' is selected)",
                        related_name="analytics_included",
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Settings",
            },
        ),
    ]
