# Generated by Django 5.2.8 on 2025-12-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_starling", "0002_analyticssettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
